pyerrorschema/__init__.py,sha256=8DU8Im0fRGkYazNXc-6A-CA1Rkqa9lu43PNy9pJMvUs,205
pyerrorschema/base_error_schema.py,sha256=cGEcUlesiz7oyoUxHKXa0nsCWseRiYwhtTdmO2J6KJ4,1158
pyerrorschema/fastapi_error_schema.py,sha256=DNPO00O6cNqkijeyGlT370JyO5_ISdwsNh2Jii0ED40,1451
pyerrorschema/utils.py,sha256=B8MQqzbd-VkKWifzHbbm6W4jtM0VshDM8o6sa1cPZhY,711
pyerrorschema-0.1.2.dist-info/LICENSE.txt,sha256=A7rB4UyEX3MfqKHLzQfc4ef1KYIW7U1kcV9xCyc-_40,1530
pyerrorschema-0.1.2.dist-info/METADATA,sha256=iDGlvb3TLklKc99mIjRH5y4deGzPDrsU0xfA-Z-d8-4,3091
pyerrorschema-0.1.2.dist-info/WHEEL,sha256=GJ7t_kWBFywbagK5eo9IoUwLW6oyOeTKmQ-9iHFVNxQ,92
pyerrorschema-0.1.2.dist-info/top_level.txt,sha256=JZxuu2xBH7kHSmMrGdRiIlWORxWZgPoT138hhKkwT44,14
pyerrorschema-0.1.2.dist-info/RECORD,,
